# == Schema Information
#
# Table name: podium_podium_placers
#
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  name       :string
#  place      :integer
#  podium_id  :integer
#  updated_at :datetime         not null
#  user_id    :integer
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Podium::PodiumPlacersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Podium::PodiumPlacer. As you add validations to Podium::PodiumPlacer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Podium::PodiumPlacersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all podium_podium_placers as @podium_podium_placers" do
      podium_placer = Podium::PodiumPlacer.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:podium_podium_placers)).to eq([podium_placer])
    end
  end

  describe "GET #show" do
    it "assigns the requested podium_podium_placer as @podium_podium_placer" do
      podium_placer = Podium::PodiumPlacer.create! valid_attributes
      get :show, {:id => podium_placer.to_param}, valid_session
      expect(assigns(:podium_podium_placer)).to eq(podium_placer)
    end
  end

  describe "GET #new" do
    it "assigns a new podium_podium_placer as @podium_podium_placer" do
      get :new, {}, valid_session
      expect(assigns(:podium_podium_placer)).to be_a_new(Podium::PodiumPlacer)
    end
  end

  describe "GET #edit" do
    it "assigns the requested podium_podium_placer as @podium_podium_placer" do
      podium_placer = Podium::PodiumPlacer.create! valid_attributes
      get :edit, {:id => podium_placer.to_param}, valid_session
      expect(assigns(:podium_podium_placer)).to eq(podium_placer)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Podium::PodiumPlacer" do
        expect {
          post :create, {:podium_podium_placer => valid_attributes}, valid_session
        }.to change(Podium::PodiumPlacer, :count).by(1)
      end

      it "assigns a newly created podium_podium_placer as @podium_podium_placer" do
        post :create, {:podium_podium_placer => valid_attributes}, valid_session
        expect(assigns(:podium_podium_placer)).to be_a(Podium::PodiumPlacer)
        expect(assigns(:podium_podium_placer)).to be_persisted
      end

      it "redirects to the created podium_podium_placer" do
        post :create, {:podium_podium_placer => valid_attributes}, valid_session
        expect(response).to redirect_to(Podium::PodiumPlacer.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved podium_podium_placer as @podium_podium_placer" do
        post :create, {:podium_podium_placer => invalid_attributes}, valid_session
        expect(assigns(:podium_podium_placer)).to be_a_new(Podium::PodiumPlacer)
      end

      it "re-renders the 'new' template" do
        post :create, {:podium_podium_placer => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested podium_podium_placer" do
        podium_placer = Podium::PodiumPlacer.create! valid_attributes
        put :update, {:id => podium_placer.to_param, :podium_podium_placer => new_attributes}, valid_session
        podium_placer.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested podium_podium_placer as @podium_podium_placer" do
        podium_placer = Podium::PodiumPlacer.create! valid_attributes
        put :update, {:id => podium_placer.to_param, :podium_podium_placer => valid_attributes}, valid_session
        expect(assigns(:podium_podium_placer)).to eq(podium_placer)
      end

      it "redirects to the podium_podium_placer" do
        podium_placer = Podium::PodiumPlacer.create! valid_attributes
        put :update, {:id => podium_placer.to_param, :podium_podium_placer => valid_attributes}, valid_session
        expect(response).to redirect_to(podium_placer)
      end
    end

    context "with invalid params" do
      it "assigns the podium_podium_placer as @podium_podium_placer" do
        podium_placer = Podium::PodiumPlacer.create! valid_attributes
        put :update, {:id => podium_placer.to_param, :podium_podium_placer => invalid_attributes}, valid_session
        expect(assigns(:podium_podium_placer)).to eq(podium_placer)
      end

      it "re-renders the 'edit' template" do
        podium_placer = Podium::PodiumPlacer.create! valid_attributes
        put :update, {:id => podium_placer.to_param, :podium_podium_placer => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested podium_podium_placer" do
      podium_placer = Podium::PodiumPlacer.create! valid_attributes
      expect {
        delete :destroy, {:id => podium_placer.to_param}, valid_session
      }.to change(Podium::PodiumPlacer, :count).by(-1)
    end

    it "redirects to the podium_podium_placers list" do
      podium_placer = Podium::PodiumPlacer.create! valid_attributes
      delete :destroy, {:id => podium_placer.to_param}, valid_session
      expect(response).to redirect_to(podium_podium_placers_url)
    end
  end

end
